[[networks]]
name = "polkadot"
id = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://dot-rpc.stakeworld.io"

[[networks]]
id = "urn:ocn:polkadot:1000"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://sys.dotters.network/statemint"

[[networks]]
id = "urn:ocn:polkadot:2030"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://hk.p.bifrost-rpc.liebi.com/ws"

[[networks]]
id = "urn:ocn:polkadot:2034"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://hydradx.paras.dotters.network"

[[networks]]
id = "urn:ocn:polkadot:2004"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://wss.api.moonbeam.network"

[[networks]]
id = "urn:ocn:polkadot:2104"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://ws.manta.systems"