[[networks]]
id = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://rpc.ibp.network/polkadot"

[[networks]]
id = "urn:ocn:polkadot:1000"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://polkadot-asset-hub-rpc.polkadot.io"