[[networks]]
name = "polkadot"
id = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "smoldot"

[[networks]]
name = "asset_hub"
id = "urn:ocn:polkadot:1000"
relay = "polkadot"

  [networks.provider]
  type = "rpc"
  url = "wss://polkadot-asset-hub-rpc.polkadot.io"

[[networks]]
name = "acala"
id = "urn:ocn:polkadot:2000"
relay = "polkadot"

  [networks.provider]
  type = "smoldot"
  spec = "./chain-specs/acala.json"

[[networks]]
name = "astar"
id = "urn:ocn:polkadot:2006"
relay = "polkadot"

  [networks.provider]
  type = "smoldot"
  spec = "./chain-specs/astar.json"

[[networks]]
name = "moonbeam"
id = "urn:ocn:polkadot:2004"
relay = "polkadot"

  [networks.provider]
  type = "rpc"
  url = "wss://wss.api.moonbeam.network"

