[[networks]]
name = "polkadot"
id = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://rpc.ibp.network/polkadot"

[[networks]]
name = "asset_hub"
id = "urn:ocn:polkadot:1000"
relay = "polkadot"

  [networks.provider]
  type = "rpc"
  url = "wss://polkadot-asset-hub-rpc.polkadot.io"

[[networks]]
name = "acala"
id = "urn:ocn:polkadot:2000"
relay = "polkadot"

  [networks.provider]
  type = "rpc"
  url = "wss://acala-rpc-0.aca-api.network"

[[networks]]
name = "astar"
id = "urn:ocn:polkadot:2006"
relay = "polkadot"

  [networks.provider]
  type = "rpc"
  url = "wss://rpc.astar.network"

[[networks]]
name = "moonbeam"
id = "urn:ocn:polkadot:2004"
relay = "polkadot"

  [networks.provider]
  type = "rpc"
  url = "wss://wss.api.moonbeam.network"

[[networks]]
name = "hydradx"
id = "urn:ocn:polkadot:2034"
relay = "polkadot"

  [networks.provider]
  type = "rpc"
  url = "wss://hydradx-rpc.dwellir.com"