[[networks]]
id = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://rpc.ibp.network/polkadot"

[[networks]]
id = "urn:ocn:polkadot:1000"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://polkadot-asset-hub-rpc.polkadot.io"

[[networks]]
id = "urn:ocn:polkadot:2000"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://acala-rpc-0.aca-api.network"

[[networks]]
id = "urn:ocn:polkadot:2006"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://rpc.astar.network"

[[networks]]
id = "urn:ocn:polkadot:2004"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://wss.api.moonbeam.network"

[[networks]]
id = "urn:ocn:polkadot:2034"
relay = "urn:ocn:polkadot:0"

  [networks.provider]
  type = "rpc"
  url = "wss://hydradx-rpc.dwellir.com"