[[networks]]
name = "rococo_local_testnet"
id = 0

  [networks.provider]
  # type = "smoldot"
  # spec = "./chain-specs/rococo-local-relay.json"
  type = "rpc"
  url = "ws://127.0.0.1:9900"

[[networks]]
name = "asset-hub-local"
id = 1_000
relay = "rococo_local_testnet"

  [networks.provider]
  # type = "smoldot"
  # spec = "./chain-specs/asset-hub-local.json"
  type = "rpc"
  url = "ws://127.0.0.1:9910"
  
[[networks]]
name = "trappist-local"
id = 2_000
relay = "rococo_local_testnet"

  [networks.provider]
  # type = "smoldot"
  # spec = "./chain-specs/trappist-local.json"
  type = "rpc"
  url = "ws://127.0.0.1:9920"
